extends:
    # eslintデフォルト推奨ルール
  - 'eslint:recommended'
    # vue3推奨のルール
  - 'plugin:vue/vue3-recommended'
    # prettierのルール
  - 'prettier'

env:
  browser: true
  es2021: true
  # setup関数内でのコンパイラマクロをサポート
  vue/setup-compiler-macros: true

parserOptions:
  ecmaVersion: 12

rules: {
  'vue/multi-word-component-names': 0
}